### ISSUE TITLE
Libraries missing

### ISSUE THREAD

**Issue by thundergreen** [widapro/pixel_led_mqtt_panel#1]
First of all NICE PROJECT . I was wonderung to do something like this. But to compile we need the libraries. Would be nice if you could write up the libraries needed and also lins and a small how-to compile it then.

Would you mind uodatng your libraries used here in this project and where to find them ?

Thanks in advance

**Comment by widapro** [comment]
I updated Readme and added libraries. You can find them in the **Library manager** in Arduino IDE by name.

**Comment by thundergreen** [comment]
I get this error: 

Arduino: 1.8.9 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), ck, 26 MHz, 40MHz, DOUT (compatible), 4M (1M SPIFFS), 2, nonos-sdk 2.2.1 (legacy), v2 Lower Memory, Disabled, None, All Flash Contents, 115200"

pixel_led_mqtt_panel:30:19: error: 'D7' was not declared in this scope

 #define DATA_PIN  D7                      // WeMos D1 mini GPIO13

                   ^

C:\Users\utilisateur\Desktop\Project Matrix Dot\pixel_led_mqtt_panel-master\pixel_led_mqtt_panel\pixel_led_mqtt_panel.ino:34:40: note: in expansion of macro 'DATA_PIN'

 MD_Parola P = MD_Parola(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);

                                        ^

pixel_led_mqtt_panel:32:19: error: 'D5' was not declared in this scope

 #define CLK_PIN   D5                      // WeMos D1 mini GPIO14

                   ^

C:\Users\utilisateur\Desktop\Project Matrix Dot\pixel_led_mqtt_panel-master\pixel_led_mqtt_panel\pixel_led_mqtt_panel.ino:34:50: note: in expansion of macro 'CLK_PIN'

 MD_Parola P = MD_Parola(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);

                                                  ^

pixel_led_mqtt_panel:31:19: error: 'D6' was not declared in this scope

 #define CS_PIN    D6                      // WeMos D1 mini GPIO12

                   ^

C:\Users\utilisateur\Desktop\Project Matrix Dot\pixel_led_mqtt_panel-master\pixel_led_mqtt_panel\pixel_led_mqtt_panel.ino:34:59: note: in expansion of macro 'CS_PIN'

 MD_Parola P = MD_Parola(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);

                                                           ^

exit status 1
'D7' was not declared in this scope
