### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by viktor6** [widapro/pixel_led_mqtt_panel#13]
WeMos D1 mini

Connecting to Plusnet
............
WiFi ready
IP address: 
192.168.0.112
Ready
IP address: 192.168.0.112
subscribe objects
welcome message...
MQTT connected
New message arrived
wled/scrolleffect
PACMAN
set new scrolleffect
New message arrived
wled/zone0_text
MQTT ok
zone0 set new Text
New message arrived
wled/zone0_text
HA ok
zone0 set new Text

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffd60 end: 3fffffc0 offset: 01a0
3fffff00:  00000000 3ffefba5 3ffefb50 40205762  
3fffff10:  00000000 3ffefba5 3ffefb50 402078e8  
3fffff20:  00000015 3ffeefd8 40100324 00005427  
3fffff30:  00000000 00669884 3fff01a4 3ffee8f0  
3fffff40:  00000000 00000001 3ffefb50 402081c7  
3fffff50:  40105411 00669884 3ffeebb8 3ffee8f0  
3fffff60:  00000000 00000001 3ffefb50 40206495  
3fffff70:  3fffdad0 3ffee8e8 00000000 40206897  
3fffff80:  4020ba0d 00000001 3ffeeb58 3ffeeb58  
3fffff90:  3fffdad0 00000000 3ffee8e8 40202338  
3fffffa0:  3fffdad0 00000000 3ffeeb18 4020b4ac  
3fffffb0:  feefeffe feefeffe 3ffe8524 40100d6d  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3664, room 16 
tail 0
chksum 0xee
csum 0xee
v39c79d9b
~ld
Booting...
Connecting to Plusnet
............

**Comment by widapro** [comment]
It's **Soft WDT reset**  -  discussed here: https://github.com/widapro/pixel_led_mqtt_panel/issues/7
Please try to use the recommended approaches. May it can help you.
