### ISSUE TITLE
Binaries welcome

### ISSUE THREAD

**Issue by thundergreen** [widapro/pixel_led_mqtt_panel#2]
As there are a lot of people struckeling with libraries and compiling.. maybe a way of having binaries and a config webserver would hel herre..

Just ideas :)

**Comment by widapro** [comment]
Thank you for the new feature request. I'll put in the list of the new features adding a web server.

**Comment by thundergreen** [comment]
cool thanks i will maybe create some new icons

**Comment by upstairs-at-erics** [comment]
an AP with web page that allows user input of wifi ssid,passcode and mqtt broker would be the icing on the cake.

**Comment by widapro** [comment]
Wifi web config portal and web server for device configuration were implemented in the new version: https://community.home-assistant.io/t/mqtt-dot-matrix-display-to-show-information-from-mqtt-topics/170022/40?u=wida
